
type Gallery {
  id: Int
  title: String
  city: String
  images: String
  createdAt: String
  updatedAt: String
  gallery_category_id: Int
}

input CreateGalleryInput {
  title: String!
  city: String!
  images: String!
  gallery_category_id: Int
}

input UpdateGalleryInput {
  id: Int!
  title: String
  city: String
  images: String
  gallery_category_id: Int
}

type Query {
  gallery(id: ID!): Gallery
  allGallerys: [Gallery]
}

type Mutation {
  createGallery(input: CreateGalleryInput): Gallery
  updateGallery(id: ID!, input: UpdateGalleryInput): Gallery
  deleteGallery(id: ID!): String
}
