
type Partnership {
  id: Int
  first_name: String
  last_name: String
  full_name: String
  phone: String
  email: String
  partnership_type: String
  partnership_plan: String
  amount: String
  payment_method: String
  additional_message: String
  due_date: String
  createdAt: String
  updatedAt: String
}

input CreatePartnershipInput {
  first_name: String!
  last_name: String!
  full_name: String!
  phone: String!
  email: String!
  partnership_type: String!
  partnership_plan: String
  amount: String!
  payment_method: String!
  additional_message: String
  due_date: String
}

input UpdatePartnershipInput {
  id: Int!
  first_name: String
  last_name: String
  full_name: String
  phone: String
  email: String
  partnership_type: String
  partnership_plan: String
  amount: String
  payment_method: String
  additional_message: String
  due_date: String
}

type Query {
  partnership(id: ID!): Partnership
  allPartnerships: [Partnership]
}

type Mutation {
  createPartnership(input: CreatePartnershipInput): Partnership
  updatePartnership(id: ID!, input: UpdatePartnershipInput): Partnership
  deletePartnership(id: ID!): String
}
