
type PartnershipPayment {
  createdAt: String
  updatedAt: String
  partnership_id: Int
  payment_id: Int
}

input CreatePartnershipPaymentInput {
  
}

input UpdatePartnershipPaymentInput {
  id: Int!
  
}

type Query {
  partnershippayment(id: ID!): PartnershipPayment
  allPartnershipPayments: [PartnershipPayment]
}

type Mutation {
  createPartnershipPayment(input: CreatePartnershipPaymentInput): PartnershipPayment
  updatePartnershipPayment(id: ID!, input: UpdatePartnershipPaymentInput): PartnershipPayment
  deletePartnershipPayment(id: ID!): String
}
