
type ServiceCategory {
  id: Int
  title: String
  playlist_link: String
  createdAt: String
  updatedAt: String
}

input CreateServiceCategoryInput {
  title: String!
  playlist_link: String!
}

input UpdateServiceCategoryInput {
  id: Int!
  title: String
  playlist_link: String
}

type Query {
  servicecategory(id: ID!): ServiceCategory
  allServiceCategorys: [ServiceCategory]
}

type Mutation {
  createServiceCategory(input: CreateServiceCategoryInput): ServiceCategory
  updateServiceCategory(id: ID!, input: UpdateServiceCategoryInput): ServiceCategory
  deleteServiceCategory(id: ID!): String
}
