
type Service {
  id: Int
  youtube_link: String
  createdAt: String
  updatedAt: String
  service_category_id: Int
}

input CreateServiceInput {
  youtube_link: String!
  service_category_id: Int
}

input UpdateServiceInput {
  id: Int!
  youtube_link: String
  service_category_id: Int
}

type Query {
  service(id: ID!): Service
  allServices: [Service]
}

type Mutation {
  createService(input: CreateServiceInput): Service
  updateService(id: ID!, input: UpdateServiceInput): Service
  deleteService(id: ID!): String
}
