
type Token {
  id: Int
  token: String
  expiryDate: String
  userId: Int
  createdAt: String
  updatedAt: String
}

input CreateTokenInput {
  token: String!
  expiryDate: String!
  userId: Int
}

input UpdateTokenInput {
  id: Int!
  token: String
  expiryDate: String
  userId: Int
}

type Query {
  token(id: ID!): Token
  allTokens: [Token]
}

type Mutation {
  createToken(input: CreateTokenInput): Token
  updateToken(id: ID!, input: UpdateTokenInput): Token
  deleteToken(id: ID!): String
}
