
type VisitorSchedule {
  id: Int
  date: String
  start_time: String
  end_time: String
  availabile: Boolean
  status: String
  payment_amount_usd: String
  payment_amount_etb: String
  pickup_extra_payment_usd: String
  pickup_extra_payment_etb: String
  createdAt: String
  updatedAt: String
}

input CreateVisitorScheduleInput {
  date: String!
  start_time: String!
  end_time: String!
  availabile: Boolean!
  status: String!
  payment_amount_usd: String!
  payment_amount_etb: String!
  pickup_extra_payment_usd: String!
  pickup_extra_payment_etb: String!
}

input UpdateVisitorScheduleInput {
  id: Int!
  date: String
  start_time: String
  end_time: String
  availabile: Boolean
  status: String
  payment_amount_usd: String
  payment_amount_etb: String
  pickup_extra_payment_usd: String
  pickup_extra_payment_etb: String
}

type Query {
  visitorschedule(id: ID!): VisitorSchedule
  allVisitorSchedules: [VisitorSchedule]
}

type Mutation {
  createVisitorSchedule(input: CreateVisitorScheduleInput): VisitorSchedule
  updateVisitorSchedule(id: ID!, input: UpdateVisitorScheduleInput): VisitorSchedule
  deleteVisitorSchedule(id: ID!): String
}
