input CreateBookPurchaseInput {
  first_name: String!
  last_name: String!
  phone: String!
  email: String!
  payment_method: String!
  amount: Float!
}

type ChapaPaymentResponseData {
  checkout_url: String!
}

type ChapaPaymentResponse {
  message: String!
  status: String!
  data: ChapaPaymentResponseData!
}

type Mutation {
  chapaBookPurchase(input: CreateBookPurchaseInput): ChapaPaymentResponse!

  # for paypal
  createBookPurchaseOrder(input: CreateBookPurchaseInput): JSON!
  captureBookPurchaseOrder(orderID: String!): JSON!
}
