# import '../generated/schema.graphql'

input CreateGalleryCategoryInput {
  title: String!
}

input UpdateGalleryCategoryInput {
  id: Int!
  title: String!
}

input CreateGalleryInput {
  title: String!
  images: [String!]!
  city: String!
  gallery_category_id: Int!
}

input UpdateGalleryInput {
  id: Int!
  title: String
  image: String
  gallery_category_id: Int
}

type Query {
  galleries: [Gallery!]!
  galleriesForUsers: [Gallery!]!

  galleryCategories: [GalleryCategory!]!
  galleryCategoryForUsers: [GalleryCategory!]!
}

type Mutation {
  createGallery(input: CreateGalleryInput): Gallery!
  updateGallery(input: UpdateGalleryInput): Boolean!
  deleteGallery(id: Int!): Boolean!

  createGalleryCategory(input: CreateGalleryCategoryInput): GalleryCategory!
  updateGalleryCategory(input: UpdateGalleryCategoryInput): Boolean!
  deleteGalleryCategory(id: Int!): Boolean!
}
