#import '../generated/schema.graphql'

input CreatePartnerInput {
  package_id: Int!

  first_name: String!
  last_name: String!
  phone: String!
  email: String!
  password: String!

  currency: String!

  gender: String
  address: String
  dob: String
}

input UpdatePartnerInput {
  package_id: Int!

  first_name: String!
  last_name: String!
  phone: String!
  email: String!
  password: String!
  currency: String!

  gender: String
  address: String
  dob: String
}

type Query {
  getPartners: [Partner]
  getPartner(id: ID!): Partner
}

type Mutation {
  createPartner(input: CreatePartnerInput!): Partner
  updatePartner(id: ID!, input: UpdatePartnerInput!): Partner
  deletePartner(id: ID!): Boolean
}
