# import '../generated/schema.graphql'

input CreatePartnershipInput {
  first_name: String!
  last_name: String!
  phone: String!
  email: String!
  payment_method: String!
  partnership_type: String!
  partnership_plan: String
  church_name: String
  address: String
  amount: Float!
  currency: String
  plan: String
  additional_message: String!
}

type ChapaPaymentResponseData {
  checkout_url: String!
}

type ChapaPaymentResponse {
  message: String!
  status: String!
  data: ChapaPaymentResponseData!
}

type Query {
  partnership(id: Int!): Partnership
  partners: [Partnership]!
}

type Mutation {
  createPartnership(input: CreatePartnershipInput): ChapaPaymentResponse!

  # for paypal
  createOrder(input: CreatePartnershipInput): JSON!
  captureOrder(orderID: String!): JSON!
  createSubscription(input: CreatePartnershipInput): JSON!
  captureSubscription(orderID: String!): JSON!

  addNewPartner(input: CreatePartnershipInput): Partnership!
}

type Subscription {
  paymentSuccessful(tx_ref: String): Boolean!
  paymentVerified(tx_ref: String): Boolean!
}
