# import '../generated/schema.graphql'

input CreateServiceCategoryInput {
  title: String!
  playlist_link: String!
}

input UpdateServiceCategoryInput {
  id: Int!
  title: String!
  playlist_link: String!
}

input CreateServiceInput {
  service_day: String
  service_date: Date
  youtube_link: String!
  service_category_id: Int!
}

input UpdateServiceInput {
  id: Int!
  service_day: String
  service_date: Date
  youtube_link: String
  service_category_id: Int
}

type Query {
  services: [Service!]!
  servicesForUsers: [Service!]!

  serviceCategories: [ServiceCategory!]!
  serviceCategoryForUsers: [ServiceCategory!]!
}

type Mutation {
  createService(input: CreateServiceInput): Service!
  updateService(input: UpdateServiceInput): Boolean!
  deleteService(id: Int!): Boolean!

  createServiceCategory(input: CreateServiceCategoryInput): ServiceCategory!
  updateServiceCategory(input: UpdateServiceCategoryInput): Boolean!
  deleteServiceCategory(id: Int!): Boolean!
}
